/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/auths/github/callback': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['github_callback'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auths/github/state': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['get_state'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @description 用于响应错误响应的通用响应体 */
		ErrRes: {
			/**
			 * Format: int32
			 * @description ❌ 错误响应 http 状态码
			 */
			code: number;
			/** @description 💬 错误响应描述性文本 */
			message: string;
		};
		/** @description 从github OAuth界面重定向回服务时github请求携带的请求体 */
		GithubCallback: {
			/**
			 * @description 收到的作为对用户同意使用github进行登陆的响应的代码。
			 * @example A.u2r=n?N^Ea3Y5.?rLzF+U0ce
			 */
			code: string;
			/**
			 * @description 不可猜测的随机字符串，用于防止跨站请求伪造攻击。
			 * @example VrEaJ191gmyuhB5CKq0x
			 */
			state: string;
		};
		/** @description 在从当前服务重定向到github OAuth界面需要的一个不可猜测的随机字符串，
		 *     用于防止跨站请求伪造攻击 */
		GithubState: {
			/**
			 * @description 不可猜测的随机字符串
			 * @example VrEaJ191gmyuhB5CKq0x
			 */
			state: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	github_callback: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['GithubCallback'];
			};
		};
		responses: {
			/** @description empty body with jwt token in the header */
			200: {
				headers: {
					/** @description New jwt token */
					Authorization?: string;
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description github state not found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrRes'];
				};
			};
			/** @description github api fail */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ErrRes'];
				};
			};
		};
	};
	get_state: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description 在从当前服务重定向到github OAuth界面需要的一个不可猜测的随机字符串，用于防止跨站请求伪造攻击 */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GithubState'];
				};
			};
		};
	};
}
